### ISSUE TITLE
Update the makefile in repo.

### ISSUE THREAD

**Issue by c1ydehhx** [NOOBDY/OOP#1]
Hi, I am Xuan, the OOP TA.
I have seen a lot of students in this course use this repo to build the CMake development environment while I mark assignments.
Because they don't remove the README.md so I can find this repo.
Thank you to your contribution, but:
 
- [HW#2 Makefile](http://140.124.183.78/gitlab/109000000/oop2022f_hw/-/blob/master/makefile) has been released, please update it if necessery.
 - HW#1, HW#2 `makefile` was released, **but once the makefile is not released anymore (HW#3, HW#4, midterm, ...), you should write your own source code, or it will cause cheating.**

Xuan.

**Comment by NOOBDY** [comment]
Hi,
Thanks for the heads up. As far as my experience goes, although my `Makefile` is kind of a hack, it does work on Jenkins. I have also written instructions on how to update the `CMakeLists.txt` file, I'll try to make it more detailed if necessary.
As for uploading the source code, a part of the purpose of this repo is to keep a backup of my files when accessing the VPN is inconvenient for me. Perhaps I can keep my files on a separate branch because most people I know that use this repo doesn't know how `git checkout` works lol and also I will try to delay the update on this repo.
